### ISSUE TITLE
cardContent Handeling

### ISSUE THREAD

**Issue by zottelbeyer** [NFCdroid/nfcapp#5]
Im Moment wird in der Funktion extractCardInformation (VCardFormatTool) jede Eigenschaft [name, tel, tel, email] am Ende des ListArrays eingefügt sofern vorhanden.

Da wir noch geplant hatten die Strings "Name: " "Telefon-Mobil: " etc zu entfernen wird eine Zuordnung in Zukunft nicht mehr möglich sein.

Ich schlage deshalb vor dass wir jedem Inhalt ein festes Feld im Array zuweisen nach folgendem Schema:
0) name
1) phone_mobile
2) phone_home
3) email

bei nicht vorhandenen Infos einfach einen leeren String damit wir eine null-pointer-exception vermeiden.

**Comment by ohli** [comment]
Ok, das sollte so reichen. Ich glaube da bietet sich sogar ein
zweidimensionales Array an, da sind dann alle Felder entsprechend
reserviert und lassen sich notfalls erweitern.

Dafür!

Am 15.12.2015 um 11:32 schrieb zottelbeyer:

**Comment by zottelbeyer** [comment]
Oder einfach ein Objekt was man dann auch noch erweitern könnte.
